[32m[2019-11-25 14:51:20,527] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[32m[2019-11-25 14:51:35,446] [logger.py:98] [logger:__console] [INFO]- 打开网页成功！[0m
[32m[2019-11-25 14:51:44,173] [logger.py:98] [logger:__console] [INFO]- 登录成功！[0m
[32m[2019-11-25 14:59:15,198] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 14:59:31,535] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 15:10:30,926] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:10:30,933] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：(1146, "Table 'sign_db_test.user_tbl' doesn't exist")[0m
[32m[2019-11-25 15:10:37,861] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:10:37,868] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：(1146, "Table 'sign_db_test.user_tbl' doesn't exist")[0m
[32m[2019-11-25 15:11:24,955] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:11:24,964] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：(1146, "Table 'sign_db_test.user_tbl' doesn't exist")[0m
[32m[2019-11-25 15:11:39,294] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:11:39,300] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：(1054, "Unknown column '%道在%' in 'where clause'")[0m
[32m[2019-11-25 15:11:55,767] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 15:12:20,691] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:12:20,700] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：'NoneType' object is not subscriptable[0m
[32m[2019-11-25 15:12:50,181] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 15:20:07,389] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:23:24,069] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:24:42,419] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:26:46,653] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:27:28,767] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:27:36,198] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:27:46,907] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:29:29,841] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:34:27,640] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[31m[2019-11-25 15:34:27,647] [logger.py:104] [logger:__console] [ERROR]- 执行SQL语句出现异常：(1146, "Table 'xxbmm-course_test.customer_tbl' doesn't exist")[0m
[32m[2019-11-25 15:34:43,719] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 15:35:26,075] [logger.py:98] [logger:__console] [INFO]- 数据库连接成功[0m
[32m[2019-11-25 15:39:23,325] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 15:40:33,948] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 16:42:01,246] [logger.py:98] [logger:__console] [INFO]- 本地 数据库连接成功[0m
[32m[2019-11-25 16:42:06,642] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 16:42:17,106] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 16:43:16,963] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[32m[2019-11-25 16:43:29,684] [logger.py:98] [logger:__console] [INFO]- 打开网页成功！[0m
[32m[2019-11-25 16:43:33,013] [logger.py:98] [logger:__console] [INFO]- 登录成功！[0m
[32m[2019-11-25 17:01:45,839] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[32m[2019-11-25 17:01:58,656] [logger.py:98] [logger:__console] [INFO]- 打开网页成功！[0m
[32m[2019-11-25 17:02:07,569] [logger.py:98] [logger:__console] [INFO]- 登录成功！[0m
[32m[2019-11-25 17:12:45,708] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:13:01,248] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:13:42,413] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:13:57,916] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:16:52,308] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:17:07,756] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:19:59,772] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:20:15,228] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:22:32,635] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:22:48,080] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:23:29,491] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:23:44,942] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:24:24,500] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:24:44,959] [logger.py:104] [logger:__console] [ERROR]- 打开http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:27:52,337] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 17:27:52,337] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:28:12,841] [logger.py:104] [logger:__console] [ERROR]- 打开 http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:30:14,505] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 17:30:14,506] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:30:34,935] [logger.py:104] [logger:__console] [ERROR]- 打开 http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:30:56,716] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
[32m[2019-11-25 17:33:49,789] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 17:33:49,789] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:34:05,278] [logger.py:104] [logger:__console] [ERROR]- 打开 http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:34:21,933] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
[32m[2019-11-25 17:35:21,300] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 17:35:21,301] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[32m[2019-11-25 17:35:44,508] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
[32m[2019-11-25 17:40:59,958] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 17:40:59,959] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 17:41:15,445] [logger.py:104] [logger:__console] [ERROR]- 打开 http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 17:41:32,095] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
[32m[2019-11-25 18:44:10,096] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 18:44:10,097] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[31m[2019-11-25 18:44:25,649] [logger.py:104] [logger:__console] [ERROR]- 打开 http://www.easytest.xyz/index/ 页面加载超时！Message: timeout
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.18362 x86_64)
[0m
[32m[2019-11-25 18:44:49,710] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
[32m[2019-11-25 18:44:55,552] [logger.py:98] [logger:__console] [INFO]- 测试用例：<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<paramunittest.TestLogin_0 testMethod=test_login>]>]>]>[0m
[32m[2019-11-25 18:44:55,553] [logger.py:98] [logger:__console] [INFO]- start browser name :Chrome[0m
[32m[2019-11-25 18:45:11,330] [logger.py:98] [logger:__console] [INFO]- 打开网页成功！[0m
[32m[2019-11-25 18:45:16,376] [logger.py:98] [logger:__console] [INFO]- 执行用例，生成HTML报告![0m
